import { AcademicActivity, ExecutionReport, ExtractedEvent, AuditLog, AcademicDocument, GranularityGroup } from '../types';

export const INITIAL_ACADEMIC_ACTIVITIES: AcademicActivity[] = [
  // Database Management Systems (DBMS) - CSE 3rd Year
  {
    id: 'act-dbms-u1',
    activity_id: 'CSE-DBMS-L5-0010',
    activity_name: 'DBMS Concepts & Architecture',
    level: 'L5_Activity',
    department: 'Computer Science & Engineering',
    course: 'Database Management Systems',
    unit: 'Unit 1: Introduction to DBMS',
    activity_type: 'Lecture',
    faculty: 'Prof. A. Kumar',
    class_section: 'CSE-A',
    location: 'LH-201',
    planned_start: '2025-08-01',
    planned_end: '2025-08-01',
    actual_start: '2025-08-01',
    actual_end: '2025-08-01',
    planned_content: 'DBMS Concepts, Three-Schema Architecture, Data Independence',
    actual_content: 'DBMS Concepts, Architecture, Data Independence explained',
    completion_percentage: 100,
    status: 'Completed',
    deviation_days: 0,
    deviation_status: 'On Track',
    planned_sessions: 4,
    actual_sessions: 4,
    historical_avg_sessions: 4.1,
    historical_variance_pct: 2,
    linked_event_ids: ['evt-dbms-001']
  },
  {
    id: 'act-dbms-u2',
    activity_id: 'CSE-DBMS-L5-0011',
    activity_name: 'ER Modeling & Constraints',
    level: 'L5_Activity',
    department: 'Computer Science & Engineering',
    course: 'Database Management Systems',
    unit: 'Unit 2: ER Model',
    activity_type: 'Lecture',
    faculty: 'Prof. A. Kumar',
    class_section: 'CSE-A',
    location: 'LH-201',
    planned_start: '2025-08-16',
    planned_end: '2025-08-16',
    actual_start: '2025-08-18',
    actual_end: '2025-08-18',
    planned_content: 'ER Model, Constraints, Entity Sets, Relationship Types',
    actual_content: 'ER Model, Constraints, Weak Entities, Industry Examples',
    completion_percentage: 100,
    status: 'Completed',
    deviation_days: 2,
    deviation_status: 'Delayed',
    planned_sessions: 5,
    actual_sessions: 6,
    historical_avg_sessions: 5.8,
    historical_variance_pct: 16,
    linked_event_ids: ['evt-dbms-002']
  },
  {
    id: 'act-dbms-u3',
    activity_id: 'CSE-DBMS-L5-0012',
    activity_name: 'Relational Model & Relational Algebra',
    level: 'L5_Activity',
    department: 'Computer Science & Engineering',
    course: 'Database Management Systems',
    unit: 'Unit 3: Relational Model',
    activity_type: 'Lecture',
    faculty: 'Prof. A. Kumar',
    class_section: 'CSE-A',
    location: 'LH-201',
    planned_start: '2025-08-31',
    planned_end: '2025-08-31',
    actual_start: '2025-09-03',
    actual_end: '2025-09-03',
    planned_content: 'Relational Model, Keys, Integrity Constraints, Relational Algebra',
    actual_content: 'Relational Model, Keys (Primary, Foreign, Candidate), Operators',
    completion_percentage: 100,
    status: 'Completed',
    deviation_days: 3,
    deviation_status: 'Delayed',
    planned_sessions: 6,
    actual_sessions: 7,
    historical_avg_sessions: 6.9,
    historical_variance_pct: 15,
    linked_event_ids: ['evt-dbms-003']
  },
  {
    id: 'act-dbms-u4',
    activity_id: 'CSE-DBMS-L5-0013',
    activity_name: 'SQL Query Fundamentals',
    level: 'L5_Activity',
    department: 'Computer Science & Engineering',
    course: 'Database Management Systems',
    unit: 'Unit 4: SQL Basics',
    activity_type: 'Lecture',
    faculty: 'Prof. A. Kumar',
    class_section: 'CSE-A',
    location: 'LH-201',
    planned_start: '2025-09-15',
    planned_end: '2025-09-15',
    actual_start: '2025-09-15',
    actual_end: '2025-09-15',
    planned_content: 'SELECT, WHERE, DISTINCT, ORDER BY, GROUP BY clauses',
    actual_content: 'SELECT, WHERE, DISTINCT, ORDER BY basic queries tested',
    completion_percentage: 75,
    status: 'In Progress',
    deviation_days: 0,
    deviation_status: 'On Track',
    planned_sessions: 5,
    historical_avg_sessions: 5.2,
    historical_variance_pct: 4
  },
  {
    id: 'act-dbms-u5',
    activity_id: 'CSE-DBMS-L5-0014',
    activity_name: 'Complex Queries & Joins',
    level: 'L5_Activity',
    department: 'Computer Science & Engineering',
    course: 'Database Management Systems',
    unit: 'Unit 5: Joins',
    activity_type: 'Lecture',
    faculty: 'Prof. A. Kumar',
    class_section: 'CSE-A',
    location: 'LH-201',
    planned_start: '2025-09-30',
    planned_end: '2025-09-30',
    planned_content: 'Inner Joins, Outer Joins, Correlated Subqueries, Views',
    completion_percentage: 0,
    status: 'Not Started',
    deviation_days: 0,
    deviation_status: 'Not Started',
    planned_sessions: 4,
    historical_avg_sessions: 4.5,
    historical_variance_pct: 12
  },
  {
    id: 'act-dbms-u6',
    activity_id: 'CSE-DBMS-L5-0015',
    activity_name: 'Database Normalization',
    level: 'L5_Activity',
    department: 'Computer Science & Engineering',
    course: 'Database Management Systems',
    unit: 'Unit 6: Normalization',
    activity_type: 'Lecture',
    faculty: 'Prof. A. Kumar',
    class_section: 'CSE-A',
    location: 'LH-201',
    planned_start: '2025-10-15',
    planned_end: '2025-10-15',
    planned_content: '1NF, 2NF, 3NF, BCNF, Functional Dependencies',
    completion_percentage: 0,
    status: 'Not Started',
    deviation_days: 0,
    deviation_status: 'Not Started',
    planned_sessions: 6,
    historical_avg_sessions: 7.4,
    historical_variance_pct: 23
  },

  // Data Structures (DSA) - Target for Key Demo
  {
    id: 'act-dsa-u3-ll',
    activity_id: 'CSE-DSA-L5-0042',
    activity_name: 'Singly & Doubly Linked List Implementation',
    level: 'L5_Activity',
    department: 'Computer Science & Engineering',
    course: 'Data Structures',
    unit: 'Unit III: Linked Lists',
    activity_type: 'Practical',
    faculty: 'Prof. Kumar',
    class_section: 'CSE-C',
    location: 'Lab 3 (Advanced Computing)',
    planned_start: '2026-08-25',
    planned_end: '2026-08-25',
    planned_content: 'Singly Linked List, Doubly Linked List, Insertion & Deletion Algorithms',
    completion_percentage: 0,
    status: 'Planned',
    deviation_days: 0,
    deviation_status: 'On Track',
    planned_sessions: 3,
    historical_avg_sessions: 4.2,
    historical_variance_pct: 40,
    notes: 'Key foundational practical topic before circular linked lists'
  },
  {
    id: 'act-dsa-u4-trees',
    activity_id: 'CSE-DSA-L5-0043',
    activity_name: 'Binary Search Trees & Traversal',
    level: 'L5_Activity',
    department: 'Computer Science & Engineering',
    course: 'Data Structures',
    unit: 'Unit 4: Trees',
    activity_type: 'Lecture',
    faculty: 'Prof. S. Sengupta',
    class_section: 'CSE-B',
    location: 'LH-203',
    planned_start: '2026-09-10',
    planned_end: '2026-09-10',
    actual_start: '2026-09-18',
    actual_end: '2026-09-18',
    planned_content: 'Binary Trees, BST Insert, Delete, Inorder, Preorder, Postorder',
    actual_content: 'Binary Search Tree operations and recursive traversal algorithms',
    completion_percentage: 100,
    status: 'Completed',
    deviation_days: 8,
    deviation_status: 'Delayed',
    planned_sessions: 5,
    actual_sessions: 7,
    historical_avg_sessions: 6.8,
    historical_variance_pct: 36
  },
  {
    id: 'act-se-u2-req',
    activity_id: 'CSE-SE-L5-0021',
    activity_name: 'Requirements Elicitation & SRS Modeling',
    level: 'L5_Activity',
    department: 'Computer Science & Engineering',
    course: 'Software Engineering',
    unit: 'Unit 2: Requirements Elicitation',
    activity_type: 'Lecture',
    faculty: 'Dr. Priya Mehta',
    class_section: 'CSE-A',
    location: 'LH-104',
    planned_start: '2026-08-20',
    planned_end: '2026-08-20',
    actual_start: '2026-08-24',
    actual_end: '2026-08-24',
    planned_content: 'Interviews, Use Cases, IEEE 830 SRS Standard, Feasibility Study',
    actual_content: 'SRS Documentation & Use Case Diagram practical walkthrough',
    completion_percentage: 100,
    status: 'Completed',
    deviation_days: 4,
    deviation_status: 'Delayed',
    planned_sessions: 4,
    actual_sessions: 5,
    historical_avg_sessions: 4.8,
    historical_variance_pct: 20
  },
  {
    id: 'act-dbms-lab-sql',
    activity_id: 'CSE-DBMS-L5-0018',
    activity_name: 'SQL Practical Session',
    level: 'L5_Activity',
    department: 'Computer Science & Engineering',
    course: 'Database Management Systems',
    unit: 'Unit 4: SQL Lab',
    activity_type: 'Practical',
    faculty: 'Prof. A. Kumar',
    class_section: 'CSE-B',
    location: 'Database Lab 2',
    planned_start: '2026-08-28',
    planned_end: '2026-08-28',
    planned_content: 'DDL and DML Queries Execution on PostgreSQL',
    completion_percentage: 40,
    status: 'In Progress',
    deviation_days: 0,
    deviation_status: 'On Track',
    planned_sessions: 3,
    historical_avg_sessions: 3.2,
    historical_variance_pct: 7
  },
  {
    id: 'act-dbms-sql-query-ex',
    activity_id: 'CSE-DBMS-L5-0019',
    activity_name: 'SQL Query Exercises',
    level: 'L5_Activity',
    department: 'Computer Science & Engineering',
    course: 'Database Management Systems',
    unit: 'Unit 4: SQL Basics',
    activity_type: 'Tutorial',
    faculty: 'Prof. A. Kumar',
    class_section: 'CSE-B',
    location: 'LH-201',
    planned_start: '2026-08-29',
    planned_end: '2026-08-29',
    planned_content: 'Solving nested queries, aggregate functions, HAVING clause',
    completion_percentage: 0,
    status: 'Planned',
    deviation_days: 0,
    deviation_status: 'On Track',
    planned_sessions: 2,
    historical_avg_sessions: 2.1,
    historical_variance_pct: 5
  },
  {
    id: 'act-dbms-lab-gen',
    activity_id: 'CSE-DBMS-L5-0020',
    activity_name: 'Database Lab - Schema Design',
    level: 'L5_Activity',
    department: 'Computer Science & Engineering',
    course: 'Database Management Systems',
    unit: 'Unit 2: Lab',
    activity_type: 'Practical',
    faculty: 'Prof. A. Kumar',
    class_section: 'CSE-A',
    location: 'Database Lab 1',
    planned_start: '2026-08-22',
    planned_end: '2026-08-22',
    planned_content: 'Creating tables, foreign keys, and integrity constraints in Oracle/MySQL',
    completion_percentage: 100,
    status: 'Completed',
    deviation_days: 1,
    deviation_status: 'Delayed',
    planned_sessions: 2,
    actual_sessions: 2,
    historical_avg_sessions: 2.2,
    historical_variance_pct: 10
  },
  {
    id: 'act-ai-lab',
    activity_id: 'CSE-AI-L5-0005',
    activity_name: 'A* Search and Heuristics Implementation',
    level: 'L5_Activity',
    department: 'Computer Science & Engineering',
    course: 'Artificial Intelligence',
    unit: 'Unit 2: Informed Search',
    activity_type: 'Practical',
    faculty: 'Dr. R. Sharma',
    class_section: 'CSE-A',
    location: 'AI Center of Excellence',
    planned_start: '2026-09-02',
    planned_end: '2026-09-02',
    planned_content: 'Implementation of A* algorithm with Euclidean and Manhattan heuristics',
    completion_percentage: 50,
    status: 'In Progress',
    deviation_days: 0,
    deviation_status: 'On Track',
    planned_sessions: 3,
    historical_avg_sessions: 3.5,
    historical_variance_pct: 17
  },
  {
    id: 'act-cn-u3',
    activity_id: 'CSE-CN-L5-0033',
    activity_name: 'TCP/IP Flow Control & Congestion Management',
    level: 'L5_Activity',
    department: 'Computer Science & Engineering',
    course: 'Computer Networks',
    unit: 'Unit 3: Transport Layer',
    activity_type: 'Lecture',
    faculty: 'Prof. V. Raman',
    class_section: 'CSE-B',
    location: 'LH-102',
    planned_start: '2026-08-15',
    planned_end: '2026-08-15',
    actual_start: '2026-08-21',
    actual_end: '2026-08-21',
    planned_content: 'TCP 3-Way Handshake, Sliding Window, AIMD Congestion Control',
    completion_percentage: 100,
    status: 'Completed',
    deviation_days: 6,
    deviation_status: 'Delayed',
    planned_sessions: 4,
    actual_sessions: 5,
    historical_avg_sessions: 4.9,
    historical_variance_pct: 22
  },
  {
    id: 'act-os-u2',
    activity_id: 'CSE-OS-L5-0017',
    activity_name: 'CPU Scheduling Algorithms',
    level: 'L5_Activity',
    department: 'Computer Science & Engineering',
    course: 'Operating Systems',
    unit: 'Unit 2: Process Management',
    activity_type: 'Lecture',
    faculty: 'Dr. M. Kulkarni',
    class_section: 'CSE-C',
    location: 'LH-204',
    planned_start: '2026-08-10',
    planned_end: '2026-08-10',
    planned_content: 'FCFS, SJF, Round Robin, Multi-level Queue Scheduling',
    completion_percentage: 30,
    status: 'Overdue',
    deviation_days: 12,
    deviation_status: 'Delayed',
    planned_sessions: 4,
    historical_avg_sessions: 5.1,
    historical_variance_pct: 27
  },
  {
    id: 'act-apt-quant',
    activity_id: 'TNP-APT-L5-0001',
    activity_name: 'Quantitative Aptitude Unit',
    level: 'L5_Activity',
    department: 'Training & Placement',
    course: 'Career Readiness & Soft Skills',
    unit: 'Unit 1: Numerical Reasoning',
    activity_type: 'Workshop',
    faculty: 'Trainer K. Bose',
    class_section: 'CSE-All',
    location: 'Auditorium A',
    planned_start: '2026-09-20',
    planned_end: '2026-09-20',
    planned_content: 'Time and Distance, Permutations, Probability, Data Interpretation',
    completion_percentage: 0,
    status: 'Planned',
    deviation_days: 0,
    deviation_status: 'Not Started',
    planned_sessions: 6,
    historical_avg_sessions: 6.0,
    historical_variance_pct: 0
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    event_id: 'evt-dbms-001',
    report_id: 'rep-001',
    activity_id: 'CSE-DBMS-L5-0010',
    source: 'Faculty Web Portal Form',
    source_excerpt: 'Completed introductory session on DBMS Concepts and three-tier architecture.',
    extracted_data: {
      activity: 'DBMS Concepts & Architecture',
      course: 'Database Management Systems',
      class_section: 'CSE-A',
      date: '2025-08-01'
    },
    candidate_activities: ['CSE-DBMS-L5-0010: DBMS Concepts & Architecture (96%)'],
    confidence_score: 96,
    decision: 'Automatically linked to master plan CSE-DBMS-L5-0010',
    decision_type: 'AUTO_LINKED',
    performed_by: 'AI Execution Intelligence Engine',
    timestamp: '2025-08-01T16:30:00Z',
    previous_value: 'Status: Planned, Progress: 0%',
    new_value: 'Status: Completed, Progress: 100%, Deviation: 0 Days (On Track)'
  },
  {
    id: 'aud-002',
    event_id: 'evt-dbms-002',
    report_id: 'rep-002',
    activity_id: 'CSE-DBMS-L5-0011',
    source: 'Faculty Mobile Quick Submission',
    source_excerpt: 'Finished ER model and constraints with weak entity examples today.',
    extracted_data: {
      activity: 'ER Modeling & Constraints',
      course: 'Database Management Systems',
      class_section: 'CSE-A',
      date: '2025-08-18'
    },
    candidate_activities: ['CSE-DBMS-L5-0011: ER Modeling & Constraints (92%)'],
    confidence_score: 92,
    decision: 'Automatically linked to master plan CSE-DBMS-L5-0011',
    decision_type: 'AUTO_LINKED',
    performed_by: 'AI Execution Intelligence Engine',
    timestamp: '2025-08-18T17:15:00Z',
    previous_value: 'Status: Planned, Progress: 0%',
    new_value: 'Status: Completed, Progress: 100%, Deviation: +2 Days'
  },
  {
    id: 'aud-003',
    event_id: 'evt-se-001',
    report_id: 'rep-003',
    activity_id: 'CSE-SE-L5-0021',
    source: 'Department Execution Excel Upload',
    source_excerpt: 'Unit 2 completed in Software Engineering with SRS review.',
    extracted_data: {
      activity: 'Requirements Elicitation & SRS Modeling',
      course: 'Software Engineering',
      class_section: 'CSE-A',
      date: '2026-08-24'
    },
    candidate_activities: ['CSE-SE-L5-0021: Requirements Elicitation & SRS Modeling (88%)'],
    confidence_score: 88,
    decision: 'Reviewed and confirmed by HOD Dr. R. Sharma',
    decision_type: 'HUMAN_CONFIRMED',
    performed_by: 'Dr. R. Sharma (HOD - CSE)',
    timestamp: '2026-08-25T11:00:00Z',
    previous_value: 'Status: In Progress, Progress: 50%',
    new_value: 'Status: Completed, Progress: 100%, Deviation: +4 Days'
  }
];

export const INITIAL_GRANULARITY_GROUPS: GranularityGroup[] = [
  {
    planned_activity_id: 'CSE-DSA-L5-0042',
    planned_activity_name: 'Linked List Implementation',
    course: 'Data Structures',
    unit: 'Unit III — Linked Lists',
    target_sessions: 4,
    executed_sessions: 4,
    execution_events: [
      {
        id: 'gev-01',
        sub_topic: '1. Explained singly linked lists & node pointer structures',
        faculty: 'Prof. Kumar',
        date: '2026-08-22',
        duration: '1 Hour (Classroom)',
        notes: 'Node struct, next pointers, head and null termination.'
      },
      {
        id: 'gev-02',
        sub_topic: '2. Demonstrated insertion algorithms (Beginning, End, Middle)',
        faculty: 'Prof. Kumar',
        date: '2026-08-23',
        duration: '1 Hour (Classroom)',
        notes: 'Edge cases: empty list, single element list.'
      },
      {
        id: 'gev-03',
        sub_topic: '3. Demonstrated deletion & traversal algorithms',
        faculty: 'Prof. Kumar',
        date: '2026-08-24',
        duration: '1 Hour (Classroom)',
        notes: 'Memory deallocation in C/C++.'
      },
      {
        id: 'gev-04',
        sub_topic: '4. Conducted hands-on implementation lab exercise for CSE-C',
        faculty: 'Prof. Kumar',
        date: '2026-08-25',
        duration: '2 Hours (Lab 3)',
        notes: 'Students implemented and tested complete CRUD operations.'
      }
    ]
  },
  {
    planned_activity_id: 'CSE-DBMS-L5-0010',
    planned_activity_name: 'DBMS Concepts & Architecture',
    course: 'Database Management Systems',
    unit: 'Unit 1: Introduction',
    target_sessions: 4,
    executed_sessions: 4,
    execution_events: [
      {
        id: 'gev-05',
        sub_topic: '1. File systems vs Database Management Systems',
        faculty: 'Prof. A. Kumar',
        date: '2025-07-28',
        duration: '1 Hour',
        notes: 'Data redundancy, inconsistency, access anomalies.'
      },
      {
        id: 'gev-06',
        sub_topic: '2. ANSI/SPARC 3-Schema Architecture & Data Independence',
        faculty: 'Prof. A. Kumar',
        date: '2025-07-30',
        duration: '1 Hour',
        notes: 'Physical and logical data independence.'
      },
      {
        id: 'gev-07',
        sub_topic: '3. Database languages (DDL, DML, DCL, TCL)',
        faculty: 'Prof. A. Kumar',
        date: '2025-07-31',
        duration: '1 Hour',
        notes: 'Syntax differences and transaction controls.'
      },
      {
        id: 'gev-08',
        sub_topic: '4. Database Users and Administrators responsibilities',
        faculty: 'Prof. A. Kumar',
        date: '2025-08-01',
        duration: '1 Hour',
        notes: 'Unit 1 recap and quiz.'
      }
    ]
  }
];

export const INITIAL_DOCUMENTS: AcademicDocument[] = [
  {
    id: 'doc-001',
    title: 'DBMS Master Course Execution Plan 2025-26',
    category: 'Course Plan',
    department: 'CSE',
    course: 'Database Management Systems',
    file_name: 'DBMS_Plan_Odd_Sem_2025-26.pdf',
    file_size: '2.4 MB',
    upload_date: '2025-07-15',
    uploaded_by: 'Dr. R. Sharma (HOD)',
    status: 'Indexed',
    version: 'v2.1'
  },
  {
    id: 'doc-002',
    title: 'Data Structures & Algorithms Syllabus & Lab Schedule',
    category: 'Lab Schedule',
    department: 'CSE',
    course: 'Data Structures',
    file_name: 'DSA_Lab_Manual_2026.pdf',
    file_size: '4.8 MB',
    upload_date: '2026-08-01',
    uploaded_by: 'Prof. Kumar',
    status: 'Indexed',
    version: 'v1.4'
  },
  {
    id: 'doc-003',
    title: 'AICTE Activity Compliance Report (Q1 2026)',
    category: 'AICTE Report',
    department: 'CSE',
    file_name: 'AICTE_Mandatory_Execution_Report_Q1.pdf',
    file_size: '1.9 MB',
    upload_date: '2026-08-20',
    uploaded_by: 'Academic Coordinator',
    status: 'Indexed',
    version: 'v1.0'
  },
  {
    id: 'doc-004',
    title: 'Software Engineering Course Plan & Project Milestones',
    category: 'Course Plan',
    department: 'CSE',
    course: 'Software Engineering',
    file_name: 'SE_Curriculum_Delivery_Plan.xlsx',
    file_size: '860 KB',
    upload_date: '2026-07-28',
    uploaded_by: 'Dr. Priya Mehta',
    status: 'Indexed',
    version: 'v1.2'
  },
  {
    id: 'doc-005',
    title: 'Odd Semester 2025-26 Master Academic Calendar',
    category: 'Academic Plan',
    department: 'All Departments',
    file_name: 'Institutional_Master_Calendar_2025_26.pdf',
    file_size: '3.1 MB',
    upload_date: '2025-07-01',
    uploaded_by: 'Dean of Academics',
    status: 'Indexed',
    version: 'v3.0'
  }
];

export const INITIAL_REVIEW_QUEUE: ExtractedEvent[] = [
  {
    id: 'rev-001',
    report_id: 'rep-medium-sql',
    raw_text: 'Did SQL practice today with queries.',
    activity_description: 'SQL query practice session',
    department: 'Computer Science & Engineering',
    course: 'Database Management Systems',
    unit: 'Unit 4: SQL',
    class_section: 'CSE-B',
    faculty: 'Prof. A. Kumar',
    event_date: '2026-08-28',
    delivery_mode: 'Laboratory',
    status: 'REVIEW_REQUIRED',
    confidence_score: 78,
    timestamp: '2026-08-28T16:00:00Z',
    candidates: [
      {
        activity_id: 'CSE-DBMS-L5-0018',
        activity_name: 'SQL Practical Session',
        course: 'Database Management Systems',
        unit: 'Unit 4: SQL Lab',
        semantic_score: 82,
        course_score: 95,
        class_score: 90,
        context_score: 70,
        final_confidence: 78,
        match_explanation: 'Strong semantic correlation with practical lab session for CSE-B on SQL execution.'
      },
      {
        activity_id: 'CSE-DBMS-L5-0019',
        activity_name: 'SQL Query Exercises',
        course: 'Database Management Systems',
        unit: 'Unit 4: SQL Basics',
        semantic_score: 76,
        course_score: 90,
        class_score: 85,
        context_score: 65,
        final_confidence: 73,
        match_explanation: 'Moderate match with tutorial query exercises.'
      },
      {
        activity_id: 'CSE-DBMS-L5-0020',
        activity_name: 'Database Lab - Schema Design',
        course: 'Database Management Systems',
        unit: 'Unit 2: Lab',
        semantic_score: 60,
        course_score: 85,
        class_score: 80,
        context_score: 50,
        final_confidence: 65,
        match_explanation: 'General lab overlap but schema design focuses on DDL rather than general SQL practice.'
      }
    ],
    processing_stages: {
      raw_received: true,
      extracted: true,
      normalized: true,
      candidates_retrieved: true,
      semantic_scored: true,
      decision_made: true
    }
  }
];

export const INITIAL_UNMATCHED_QUEUE: ExtractedEvent[] = [
  {
    id: 'unm-001',
    report_id: 'rep-unmatched-apt',
    raw_text: 'Conducted placement aptitude training for final years.',
    activity_description: 'Placement aptitude training',
    department: 'Training & Placement / CSE',
    course: 'Career Readiness',
    unit: 'Special Training',
    class_section: 'CSE-All',
    faculty: 'Trainer K. Bose',
    event_date: '2026-09-01',
    delivery_mode: 'Workshop',
    status: 'UNMATCHED',
    confidence_score: 38,
    timestamp: '2026-09-01T15:30:00Z',
    candidates: [
      {
        activity_id: 'TNP-APT-L5-0001',
        activity_name: 'Quantitative Aptitude Unit',
        course: 'Career Readiness & Soft Skills',
        unit: 'Unit 1: Numerical Reasoning',
        semantic_score: 42,
        course_score: 35,
        class_score: 50,
        context_score: 25,
        final_confidence: 38,
        match_explanation: 'Score below threshold (50%). Activity lacks specific syllabus mapping in Master CSE Plan.'
      }
    ],
    processing_stages: {
      raw_received: true,
      extracted: true,
      normalized: true,
      candidates_retrieved: true,
      semantic_scored: true,
      decision_made: true
    }
  }
];
